/* Absensi Digital final: username accounts and operational data live in Firebase Realtime Database only. */
import { get, onValue, push, ref, set, update, type Unsubscribe } from "firebase/database";
import { getFirebaseDatabase } from "./firebaseClient";

export type Role = "admin" | "teacher" | "student";
export type Profile = { uid: string; name: string; username: string; role: Role; status: "approved" | "pending" | "rejected"; classId?: string; className?: string; absentNo?: number };
export type SchoolClass = { id: string; name: string; level: string; teacherId: string; teacherName: string; status: "active" | "pending" | "rejected"; createdAt: number };
export type Attendance = { uid: string; studentName: string; classId: string; className: string; absentNo: number; date: string; time: string; qrToken: string; status: "HADIR" };
export type QRSession = { classId: string; token: string; date: string; expiresAt: number; active: boolean };
function db() { const value = getFirebaseDatabase(); if (!value) throw new Error("Firebase Realtime Database belum terkonfigurasi."); return value; }
const normalize = (value: string) => value.trim().toLowerCase().replace(/[^a-z0-9._-]/g, "");
async function hashPassword(value: string) { const data = new TextEncoder().encode(value); const hash = await crypto.subtle.digest("SHA-256", data); return Array.from(new Uint8Array(hash)).map(x => x.toString(16).padStart(2, "0")).join(""); }
export const todayKey = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Jakarta" }).format(new Date());
export const nextMidnight = () => { const now = new Date(); const next = new Date(now); next.setHours(24, 0, 0, 0); return next.getTime(); };
export const friendlyError = (error: unknown) => { const code = String((error as { code?: string })?.code ?? ""); if (code === "PERMISSION_DENIED") return "Firebase menolak akses. Periksa Realtime Database Rules."; return error instanceof Error ? error.message : "Terjadi kesalahan. Coba lagi."; };
export async function register(input: { name: string; username: string; password: string; role: "teacher" | "student"; classId?: string; className?: string; level?: string; absentNo?: number }) { const username = normalize(input.username); if (username.length < 3) throw new Error("Username minimal 3 karakter dan hanya boleh huruf, angka, titik, garis bawah, atau strip."); const index = await get(ref(db(), `usernames/${username}`)); if (index.exists()) throw new Error("Username sudah dipakai."); const uid = push(ref(db(), "users")).key!; const classId = input.role === "teacher" ? push(ref(db(), "classes")).key! : input.classId!; const profile: Profile = { uid, name: input.name.trim(), username, role: input.role, status: input.role === "teacher" ? "pending" : "approved", classId, className: input.className, absentNo: input.absentNo }; const passwordHash = await hashPassword(input.password); const payload: Record<string, unknown> = { [`users/${uid}`]: profile, [`usernames/${username}`]: uid, [`credentials/${username}`]: { uid, passwordHash } }; if (input.role === "teacher") payload[`classes/${classId}`] = { id: classId, name: input.className, level: input.level, teacherId: uid, teacherName: input.name.trim(), status: "pending", createdAt: Date.now() }; await update(ref(db()), payload); }
export async function login(usernameInput: string, password: string) { const username = normalize(usernameInput); const index = await get(ref(db(), `usernames/${username}`)); if (!index.exists()) throw new Error("Username atau password tidak sesuai."); const uid = String(index.val()); const credential = await get(ref(db(), `credentials/${username}`)); const profileSnapshot = await get(ref(db(), `users/${uid}`)); if (!credential.exists() || !profileSnapshot.exists()) throw new Error("Username atau password tidak sesuai."); const raw = profileSnapshot.val() as Profile; const stored = credential.val() as { uid: string; passwordHash: string }; if (stored.uid !== uid || stored.passwordHash !== await hashPassword(password)) throw new Error("Username atau password tidak sesuai."); if (raw.status !== "approved") throw new Error(raw.status === "pending" ? "Akun masih menunggu persetujuan admin." : "Akun ditolak admin."); return raw; }
export async function logout() { localStorage.removeItem("absensi-profile"); }
export function watchClasses(callback: (items: SchoolClass[]) => void): Unsubscribe { return onValue(ref(db(), "classes"), snapshot => { const value = (snapshot.val() ?? {}) as Record<string, unknown>; callback(Object.values(value).filter((x): x is SchoolClass => { const item = x as Partial<SchoolClass>; return Boolean(item && item.status === "active"); })); }, error => console.warn(error)); }
export function watchPendingTeachers(callback: (items: Profile[]) => void): Unsubscribe { return onValue(ref(db(), "users"), snapshot => { const value = (snapshot.val() ?? {}) as Record<string, unknown>; callback(Object.values(value).filter((x): x is Profile => { const item = x as Partial<Profile>; return Boolean(item && item.role === "teacher" && item.status === "pending"); })); }, error => console.warn(error)); }
export function watchAllTeachers(callback: (items: Profile[]) => void): Unsubscribe { return onValue(ref(db(), "users"), snapshot => { const value = (snapshot.val() ?? {}) as Record<string, unknown>; callback(Object.values(value).filter((x): x is Profile => { const item = x as Partial<Profile>; return Boolean(item && item.role === "teacher"); })); }, error => console.warn(error)); }
export function watchClass(classId: string, callback: (item: SchoolClass | null) => void): Unsubscribe { return onValue(ref(db(), `classes/${classId}`), snapshot => callback(snapshot.exists() ? snapshot.val() as SchoolClass : null), error => console.warn(error)); }
export function watchTodayAttendance(classId: string, callback: (items: Attendance[]) => void): Unsubscribe { return onValue(ref(db(), `attendance/${todayKey()}/${classId}`), snapshot => { const value = (snapshot.val() ?? {}) as Record<string, unknown>; callback(Object.values(value) as Attendance[]); }, error => console.warn(error)); }
export async function approveTeacher(profile: Profile, approved: boolean) { const status = approved ? "approved" : "rejected"; await update(ref(db()), { [`users/${profile.uid}/status`]: status, [`classes/${profile.classId}/status`]: approved ? "active" : "rejected" }); }
export async function createQR(classId: string) { const token = crypto.randomUUID().replaceAll("-", ""); const session: QRSession = { classId, token, date: todayKey(), expiresAt: nextMidnight(), active: true }; await set(ref(db(), `qrSessions/${classId}`), session); return session; }
export async function readQR(classId: string) { const snapshot = await get(ref(db(), `qrSessions/${classId}`)); return snapshot.exists() ? snapshot.val() as QRSession : null; }
export async function recordAttendance(profile: Profile, payload: QRSession) { if (!payload || !payload.active || payload.classId !== profile.classId || payload.date !== todayKey() || payload.expiresAt <= Date.now()) throw new Error("QR tidak valid atau sudah kedaluwarsa."); const target = ref(db(), `attendance/${payload.date}/${profile.classId}/${profile.uid}`); if ((await get(target)).exists()) throw new Error("Anda sudah absen hari ini."); const attendance: Attendance = { uid: profile.uid, studentName: profile.name, classId: profile.classId!, className: profile.className!, absentNo: profile.absentNo ?? 0, date: payload.date, time: new Date().toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit" }), qrToken: payload.token, status: "HADIR" }; await set(target, attendance); return attendance; }
